version: '2.0'

services:
  backend:
    build: 
      context: backend/
    ports:
      - 8080:8080
    volumes:
      - maven-repo:/root/.m2
  frontend:
    build: 
      context: frontend/
    ports:
      - 3000:3000
  www:
    build: proxy/
    environment: 
      WEB_SERVER_URL_AND_PORT:  "http://frontend:3000"
      API_SERVER_URL_AND_PORT_AND_PATH: "http://backend:8080"
    ports:
      - 80:80

volumes:
   maven-repo: